consumer:
  user:
    routing_key: "myroute1"
    self_exchange: "selfexchange2"
    queue: "myqueue1"
  comment:
    routing_key: "myroute2"
    self_exchange: "selfexchange2"
    queue: "myqueue2"
  generic:
    routing_key: "myroute3"
    self_exchange: "selfexchange3"
    queue: "myqueue3"
  order:
    routing_key: "myroute4"
    self_exchange: "selfexchange4"
    queue: "myqueue4"